---
- ansible.builtin.import_tasks: ensure-compose-generated.yml

- name: "Apply {{ compose_service }} container configuration"
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_dir }}"
    services:
      - "{{ compose_service }}"
    state: present
  when: not ansible_check_mode
